[package]
name = "client"
version = "0.0.1"
build = "../build.rs"

[lib]
name = "altv_wasmer_runtime_client"
crate-type = ["staticlib"]

[dependencies]
wasmer-runtime = "0.4.2"
#lazy_static = "1.3.0"
libc = "0.2.58"
